- name: create user
  hosts: all
  become: yes
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        createhome: yes
        # hash password
        password: "{{ password | password_hash('sha512') }}"
        state: present


    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/chrome.yml
