---
# This is the first playbook that should be run first
# Navigate to the tasks/ directory to learn more about the tasks
- name: Setup Dev Academy computers
  hosts: all

  tasks:
    # - include_tasks: tasks/account.yml
    # - include_tasks: tasks/os.yml
    # - include_tasks: tasks/directories.yml
    - include_tasks: tasks/background.yml
    # - include_tasks: tasks/node.yml
    # - include_tasks: tasks/ssh.yml
    # - include_tasks: tasks/vscode.yml
    # - include_tasks: tasks/chrome.yml
    # - include_tasks: tasks/firefox.yml
